# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: q2-boots documentation
author: Caporaso Lab
copyright: "2024"
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid
  config:
    html_theme_options:
      logo:
        image_light: _static/dwq2-light.png
        image_dark: _static/dwq2-dark.png
      show_navbar_depth: 2

    # Don't include the prompt (or outputs) in the copied text
    copybutton_prompt_text: '>>> |\.\.\. '
    copybutton_prompt_is_regexp: true

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - _static/references.bib

repository:
  url: https://github.com/caporaso-lab/q2-boots-book
  path_to_book: book
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  favicon: _static/favicon.ico

parse:
  myst_substitutions:
    miniconda_url: "[Miniconda](https://conda.io/miniconda.html)"
